language: c
os:
    - linux
    - osx
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install freeglut3-dev; fi
    - virtualenv venv && source venv/bin/activate
    - pip install -e .
compiler:
    - clang
    - gcc
script:
    - cd $TRAVIS_BUILD_DIR/python_examples/simple_orbit/ && python problem.py
    - make
    - cd $TRAVIS_BUILD_DIR/examples/J2/ && make
    - cd $TRAVIS_BUILD_DIR/examples/bouncing_balls/ && make
    - cd $TRAVIS_BUILD_DIR/examples/bouncing_balls_corners/ && make
    - cd $TRAVIS_BUILD_DIR/examples/bouncing_string/ && make
    - cd $TRAVIS_BUILD_DIR/examples/circumplanetarydust/ && make
    - cd $TRAVIS_BUILD_DIR/examples/closeencounter/ && make
    - cd $TRAVIS_BUILD_DIR/examples/closeencounter_hybrid/ && make
    - cd $TRAVIS_BUILD_DIR/examples/closeencounter_record/ && make
    - cd $TRAVIS_BUILD_DIR/examples/dragforce/ && make
    - cd $TRAVIS_BUILD_DIR/examples/eccentric_orbit/ && make
    - cd $TRAVIS_BUILD_DIR/examples/forced_migration/ && make
    - cd $TRAVIS_BUILD_DIR/examples/granulardynamics/ && make
    - cd $TRAVIS_BUILD_DIR/examples/kozai/ && make
    - cd $TRAVIS_BUILD_DIR/examples/megno/ && make
    - cd $TRAVIS_BUILD_DIR/examples/mergers/ && make
    - cd $TRAVIS_BUILD_DIR/examples/outer_solar_system/ && make
    - cd $TRAVIS_BUILD_DIR/examples/overstability/ && make
    - cd $TRAVIS_BUILD_DIR/examples/prdrag/ && make
    - cd $TRAVIS_BUILD_DIR/examples/restarting_simulation/ && make
    - cd $TRAVIS_BUILD_DIR/examples/restricted_threebody/ && make
    - cd $TRAVIS_BUILD_DIR/examples/selfgravity_disc/ && make
    - cd $TRAVIS_BUILD_DIR/examples/selfgravity_plummer/ && make
    - cd $TRAVIS_BUILD_DIR/examples/shearing_sheet/ && make
    - cd $TRAVIS_BUILD_DIR/examples/shearing_sheet_2/ && make
    - cd $TRAVIS_BUILD_DIR/examples/shearing_sheet_profiling/ && make
    - cd $TRAVIS_BUILD_DIR/examples/solar_system/ && make
    - cd $TRAVIS_BUILD_DIR/examples/spreading_ring/ && make
    - cd $TRAVIS_BUILD_DIR/examples/star_of_david/ && make
    - cd $TRAVIS_BUILD_DIR/examples/stark/ && make
    - cd $TRAVIS_BUILD_DIR/examples/viewer/ && make

# Ignoring examples with complicated dependencies
#    - cd $TRAVIS_BUILD_DIR/examples/opencl/ && make
#    - cd examples/restricted_threebody_mpi/ && make
#    - cd examples/shearing_sheet_fft/ && make
#    - cd examples/selfgravity_disc_grape/ && make
#    - cd examples/shearing_sheet_grape/ && make
