install:
    - sudo apt-get install freeglut3-dev
compiler:
    - clang
    - gcc
script:
    - make
    - cd examples/J2/ && make
    - cd examples/bouncing_balls/ && make
    - cd examples/bouncing_balls_corners/ && make
    - cd examples/bouncing_string/ && make
    - cd examples/circumplanetarydust/ && make
    - cd examples/closeencounter/ && make
    - cd examples/closeencounter_hybrid/ && make
    - cd examples/closeencounter_record/ && make
    - cd examples/dragforce/ && make
    - cd examples/eccentric_orbit/ && make
    - cd examples/forced_migration/ && make
    - cd examples/granulardynamics/ && make
    - cd examples/kozai/ && make
    - cd examples/megno/ && make
    - cd examples/mergers/ && make
    - cd examples/opencl/ && make
    - cd examples/outer_solar_system/ && make
    - cd examples/overstability/ && make
    - cd examples/prdrag/ && make
    - cd examples/restarting_simulation/ && make
    - cd examples/restricted_threebody/ && make
    - cd examples/selfgravity_disc/ && make
    - cd examples/selfgravity_plummer/ && make
    - cd examples/shearing_sheet/ && make
    - cd examples/shearing_sheet_2/ && make
    - cd examples/shearing_sheet_profiling/ && make
    - cd examples/solar_system/ && make
    - cd examples/spreading_ring/ && make
    - cd examples/star_of_david/ && make
    - cd examples/stark/ && make
    - cd examples/viewer/ && make

# Ignoring examples with complicated dependencies
#    - cd examples/restricted_threebody_mpi/ && make
#    - cd examples/shearing_sheet_fft/ && make
#    - cd examples/selfgravity_disc_grape/ && make
#    - cd examples/shearing_sheet_grape/ && make
