language: python
sudo: false


env:
  - TESTPART=C
  - TESTPART=PYTHON
  - TESTPART=IPYTHON

matrix:
  include:
    - python: "2.7"
      env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.16 matplotlib=1.4"
    - python: "3.4"
      env: DEPS="libgfortran=1.0 numpy=1.9 scipy=0.16 matplotlib=1.4"
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib"

addons:
    apt:
        packages:
            - freeglut3-dev
            - openmpi-bin 
            - libopenmpi-dev
install:
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS setuptools coverage python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
    - cd $TRAVIS_BUILD_DIR && coverage run --source=rebound setup.py test
    - cd $TRAVIS_BUILD_DIR/examples/ && make
    - cd $TRAVIS_BUILD_DIR/src && make clean
    - cd $TRAVIS_BUILD_DIR/ && make  
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py AdvWHFast.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Checkpoints.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Churyumov-Gerasimenko.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py CloseEncounters.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py EscapingParticles.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Forces.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py FourierSpectrum.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Horizons.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Megno.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Resonances_of_Jupiters_moons.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py VariationalEquations.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py VariationalEquationsWithChainRule.ipynb 
    #- cd $TRAVIS_BUILD_DIR/python_tutorials/ && python ipynb2py.py Parallel.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py ParticleIDsAndRemoval.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py PoincareMap.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py OrbitalElements.ipynb 
    #- cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Testparticles.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py Units.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py WHFast.ipynb 
    - cd $TRAVIS_BUILD_DIR/ipython_examples/ && python ipynb2py.py TransitTimingVariations.ipynb 
    - cd $TRAVIS_BUILD_DIR/python_examples/dragforce/ && python problem.py
    #- cd $TRAVIS_BUILD_DIR/python_examples/horizons/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/longtermtest/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/megno/ && python problem.py
    #- cd $TRAVIS_BUILD_DIR/python_examples/megno_interactive/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/megno_simple/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/orbital_elements/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/outersolarsystem/ && python problem.py
    - cd $TRAVIS_BUILD_DIR/python_examples/simple_orbit/ && python problem.py
    - cd $TRAVIS_BUILD_DIR 

after_success:
    coveralls
